// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Item struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Order struct {
	ID     string `json:"id"`
	IsDone bool   `json:"is_done"`
}

type OrderItem struct {
	ID      int32  `json:"id"`
	OrderID string `json:"order_id"`
	ItemID  int32  `json:"item_id"`
}
