services:
  database:
    container_name: "database"
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432