services:
  app:
    tty: true
    container_name: "app"
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum


  database:
    container_name: "database"
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: