@order_id = 9e43cc3fce43f68
@auth_key= qwerty123

### create new order with items
POST localhost:8080/orders
Content-Type: application/json

{
  "item_ids": [
    1,
    1,
    2
  ]
}


### add items to an existing order
POST localhost:8080/orders/{{order_id}}/items
Content-Type: application/json


[
  1,
  1,
  2
]


### get order info
GET localhost:8080/orders/{{order_id}}


### set order as done
POST localhost:8080/orders/{{order_id}}/done
X-Auth-Key: {{auth_key}}


### get all orders
GET localhost:8080/orders
X-Auth-Key: {{auth_key}}


### get all not done orders
GET localhost:8080/orders?done=0
X-Auth-Key: {{auth_key}}


### get all done orders
GET localhost:8080/orders?done=1
X-Auth-Key: {{auth_key}}